with account_data as (
    select * from {{ ref ('stg_salesforce__account') }}
    where account_id is not null
)
select 
        {{ dbt_utils.generate_surrogate_key(['account_id']) }}	as dim_account_key,
        account_id,
        isdeleted as is_deleted,
        masterrecordid as master_recordid,
        name as account_name,
        type as account_type,
        parentid,
        billingstreet as billing_street,
        billingcity as billing_city,
        billingstate as billing_state,
        billingpostalcode as billing_postalcode,
        billingcountry as billing_country,
        shippingstreet as shipping_street,
        shippingcity as shipping_city,
        shippingstate as shipping_state,
        shippingpostalcode as shipping_postalcode,
        shippingcountry as shipping_country,
        phone,
        fax,
        accountnumber as account_number,
        website,
        sic,
        industry,
        --annualrevenue as annual_revenue,
        numberofemployees as number_of_employees,
        ownership,
        tickersymbol,
        description,
        rating,
        site,
        ownerid,
        createddate as account_created_date,
        createdbyid as account_createdby_id,
        lastmodifieddate as account_lastmodified_date,
        lastmodifiedbyid as account_lastmodifiedby_id,
        systemmodstamp,        
        cleanstatus as clean_status,
        accountsource as account_source,        
        yearstarted as year_started,
        customerpriority__c as customer_priority,
        sla__c as sla,
        active__c as active,
        numberoflocations__c as number_oflocations,
        upsellopportunity__c as upsell_opportunity,
        slaserialnumber__c as sla_serial_number,
        slaexpirationdate__c as sla_expiration_date
    from account_data    